"""Specialist scaffolder — generate a governed offensive-test specialist from a spec.

**The leash is the template, not the agent.** Every specialist this produces inherits
the same fixed governance skeleton — refused when halted, scope-guarded BEFORE the
human approval gate is ever opened, every action appended to the tamper-evident audit
chain — copied verbatim into the generated file. The operator supplies only the probe
body and metadata (*what* to test), never *whether* it is governed. It is therefore
structurally impossible to scaffold a specialist that escapes the leash: the four
governance anchors are a non-parameterized string, and the generated capability is
always ``eng.cap_for(<label>)`` — never the root capability.

    python -m tools.scaffolder \\
        --name graphql_introspection --owasp-class "OWASP API8" \\
        --target-path "/graphql" --payload "{__schema{types{name}}}" \\
        --marker "__schema" \\
        --description "Confirm GraphQL introspection exposure on an in-scope endpoint."

Generated specialists target **authorized lab targets only**. The runtime scope guard
blocks out-of-scope probes, but authorizing the target up front is the operator's duty.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from string import Template

# Names/descriptions that frame the agent as a weapon rather than an authorized tester
# are refused — responsible framing is a precondition, not a suggestion.
_BANNED_WORDS = ("attacker", "exploiter", "exfiltrator", "pwner", "backdoor", "stealer", "weapon", "malware")
_SLUG = re.compile(r"^[a-z][a-z0-9_]*$")
# Free text that lands in a docstring / f-string / comment must not be able to break
# out of it. (Literal positions — _MARKER / _PAYLOAD — are json.dumps-encoded instead,
# so a payload may freely contain quotes and braces.)
_BREAKOUT = re.compile(r'["\\${}\n\r`]')
_PATH_OK = re.compile(r"^[A-Za-z0-9_\-./?=&%:+~]*$")
_CONFIRM_MODES = ("marker_in_body", "status_5xx", "status_delta")
_SEVERITIES = ("critical", "high", "medium", "low")
_BENIGN = "leashBENIGN0"  # baseline marker for the status_delta differential

_TOOLS_DIR = Path(__file__).resolve().parent
_OUT_DIR = _TOOLS_DIR / "scaffold_out"

# ---------------------------------------------------------------------------
# The generated module. The governance skeleton ($-substitution leaves Python
# braces untouched) is FIXED — only $name/$label/$payload/$marker/$meta vary, and
# the mode-specific probe goes in $url_setup / $request_confirm, never between the
# four leash anchors (refuse_if_halted -> ensure_leading_slash -> scope_guard -> gate).
# ---------------------------------------------------------------------------
_MODULE = Template('''"""$human_title — a governed $vuln_label test specialist (generated by tools.scaffolder).

$description

Governed exactly like the hand-written specialists: refused when halted, bounded by the
scope guard before the gate is ever opened, and blocked behind the code-enforced human
approval gate before any request leaves. This file was generated from a fixed template;
only the probe body and metadata were supplied, so the leash is structural. Authorized
lab targets only.
"""
from __future__ import annotations

from urllib.parse import quote

import httpx
from pydantic import BaseModel, Field

from governance.scope_guard import ScopeViolationError, scope_guard
from swarm.control_channel import enforce_gate
from tools._subprocess import ensure_leading_slash

_MARKER = $marker
_PAYLOAD = $payload
_BENIGN = $benign

_GATE_DENIED = (
    "BLOCKED: human approval required before exploitation. The operator halted "
    "or did not approve this action at the Control Center gate."
)


def ${name}_tools(eng, *, gate_timeout: float = 600.0, gate_poll: float = 0.4):
    cap = lambda: eng.cap_for("$label")  # noqa: E731 (terse local, mirrors sqli_tools)

    async def _gate(tool: str, endpoint: str, detail: str) -> bool:
        """Pass iff the operator has approved this endpoint; otherwise open the
        Control Center gate and block on their decision — enforced in code."""
        if eng.is_approved(endpoint):
            return True
        return await enforce_gate(
            eng, tool=tool, endpoint=endpoint, detail=detail, timeout=gate_timeout, poll=gate_poll
        )

    class ${camel}ProbeInput(BaseModel):
        """$docstring"""

        path: str = Field(
            default="$target_path",
            description="In-scope endpoint path to test, e.g. $target_path",
        )

    async def ${name}_probe(args: ${camel}ProbeInput) -> str:
        halted = await eng.refuse_if_halted("${name}_probe")
        if halted:
            return halted
        base = ensure_leading_slash(args.path)
        # Scope is checked BEFORE the gate (mirrors sqli_tools): an out-of-scope reach
        # fails closed by construction without ever bothering the operator.
$url_setup
        try:
            scope_guard(probe_url, cap())
        except ScopeViolationError as e:
            await eng.log("error", tool="${name}_probe", path=base, blocked=str(e))
            return f"BLOCKED by scope guard: {e}"
        if not await _gate("${name}_probe", base, "$detail"):
            return _GATE_DENIED

$request_confirm
        await eng.log(
            "tool_result", tool="${name}_probe", path=base, status=resp.status_code, confirmed=confirmed
        )
        if confirmed:
            eng.record_finding(
                type="$finding_type",
                endpoint=base,
                severity="$severity",
                evidence="$owasp_class: $vuln_label confirmed on the endpoint (raw values, if any, redacted)",
            )
            return (
                f"[VULNERABLE] {base} — $vuln_label confirmed ($owasp_class). "
                f"$description"
            )
        return f"[not confirmed] {base}: $vuln_label not confirmed (HTTP {resp.status_code})."

    return [(${camel}ProbeInput, ${name}_probe)]
''')

# Mode-specific URL construction (placed BEFORE the fixed scope_guard) and the
# request+confirm block (placed AFTER the fixed gate). Indented to sit inside the handler.
_URL_SETUP = {
    "marker_in_body": "        probe_url = eng.base_url + base + quote(_PAYLOAD)",
    "status_5xx": "        probe_url = eng.base_url + base + quote(_PAYLOAD)",
    "status_delta": (
        "        probe_url = eng.base_url + base + quote(_PAYLOAD)\n"
        "        baseline_url = eng.base_url + base + quote(_BENIGN)"
    ),
}
_REQUEST_CONFIRM = {
    "marker_in_body": (
        "        async with httpx.AsyncClient(timeout=10.0) as client:\n"
        "            resp = await client.get(probe_url)\n"
        "        body = resp.text or \"\"\n"
        "        # Confirm only on a success response that contains the unique marker —\n"
        "        # an error page that echoes the payload is not a real finding.\n"
        "        confirmed = resp.status_code < 300 and _MARKER in body"
    ),
    "status_5xx": (
        "        async with httpx.AsyncClient(timeout=10.0) as client:\n"
        "            resp = await client.get(probe_url)\n"
        "        # The payload drove the endpoint into a server error — a signal the input\n"
        "        # reached a sink unsafely. (A clean endpoint answers < 500.)\n"
        "        confirmed = resp.status_code >= 500"
    ),
    "status_delta": (
        "        async with httpx.AsyncClient(timeout=10.0) as client:\n"
        "            baseline = await client.get(baseline_url)\n"
        "            resp = await client.get(probe_url)\n"
        "        # Differential: the payload errors where a benign baseline does not, so the\n"
        "        # error is attributable to the payload rather than a flaky endpoint.\n"
        "        confirmed = resp.status_code >= 500 and baseline.status_code < 500"
    ),
}


def _validate(args: argparse.Namespace) -> None:
    """Refuse anything that would weaken the leash or the responsible framing, BEFORE
    a single file is written."""
    if not _SLUG.match(args.name):
        raise SystemExit(f"--name must be a snake_case slug (^[a-z][a-z0-9_]*$); got {args.name!r}")
    if not _SLUG.match(args.finding_type):
        raise SystemExit(f"--finding-type must be a snake_case slug; got {args.finding_type!r}")
    if args.confirm_condition not in _CONFIRM_MODES:
        raise SystemExit(f"--confirm-condition must be one of {_CONFIRM_MODES}")
    if args.severity not in _SEVERITIES:
        raise SystemExit(f"--severity must be one of {_SEVERITIES}")
    blob = f"{args.name} {args.finding_type} {args.description}".lower()
    bad = [w for w in _BANNED_WORDS if w in blob]
    if bad:
        raise SystemExit(
            f"refused: {', '.join(bad)} frames the agent as a weapon. Use 'tester', "
            f"'detector', 'scanner', or 'sentinel' — these are authorized testers, not attack tools."
        )
    if args.confirm_condition == "marker_in_body" and not args.marker:
        raise SystemExit("--confirm-condition marker_in_body requires a non-empty --marker")
    target = args.target_path if args.target_path.startswith("/") else "/" + args.target_path
    if not target.startswith("/"):
        raise SystemExit("--target-path must resolve to an absolute path")


def _camel(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def render_module(args: argparse.Namespace) -> str:
    name = args.name
    label = "leash-" + name.replace("_", "-")
    vuln_label = args.name.replace("_", " ")
    return _MODULE.substitute(
        human_title=args.description.rstrip("."),
        description=args.description,
        vuln_label=vuln_label,
        name=name,
        camel=_camel(name),
        label=label,
        marker=args.marker or "",
        payload=args.payload,
        benign=_BENIGN,
        target_path=args.target_path if args.target_path.startswith("/") else "/" + args.target_path,
        docstring=args.description,
        detail=f"{vuln_label} probe on the endpoint",
        finding_type=args.finding_type,
        severity=args.severity,
        owasp_class=args.owasp_class,
        url_setup=_URL_SETUP[args.confirm_condition],
        request_confirm=_REQUEST_CONFIRM[args.confirm_condition],
    )


def render_roster_patch(args: argparse.Namespace) -> str:
    name = args.name
    label = "leash-" + name.replace("_", "-")
    const = f"ROLE_BRIEF_{name.upper()}"
    brief = (
        f'{const} = f"""You are the {args.name.replace("_", " ").title()} — '
        f"you confirm {args.name.replace('_', ' ')} on in-scope endpoints.\n"
        "{TEAM}\n\n"
        "CRITICAL — THE HUMAN APPROVAL GATE (enforced in code, not on trust):\n"
        f"Before testing, @mention the operator with exactly what you intend to run. Then call your "
        f"`{name}_probe` tool. The tool opens the Control Center gate and BLOCKS until the operator "
        "approves; HALT or no-approval refuses in code. Report the result honestly to @leash-commander. "
        'You can only ever reach paths your capability allows — out-of-scope calls are blocked automatically."""'
    )
    return (
        f"# --- paste into agents/roster.py ---\n\n"
        f"# 1. import (top of file):\n"
        f"from tools.{name}_tools import {name}_tools\n\n"
        f"# 2. add to the TEAM block (for @mention routing):\n"
        f'#    - @{label} — {args.name.replace("_", " ").title()}: confirms {args.name.replace("_", " ")} — only after human approval.\n\n'
        f"# 3. role brief constant:\n{brief}\n\n"
        f"# 4. add to build_swarm(eng):\n"
        f'    build_agent("{label}", {const}, {name}_tools(eng)),\n'
    )


def render_wiring_patch(args: argparse.Namespace) -> str:
    name = args.name
    label = "leash-" + name.replace("_", "-")
    return (
        f"Wiring steps for the generated specialist {label}\n"
        f"{'=' * 56}\n\n"
        f"1. tools/{name}_tools.py ........... generated (the governed probe).\n"
        f"2. tests/test_{name}_tools.py ...... write confirm / not-confirmed / out-of-scope /\n"
        f"   halted / no-approval tests (copy tests/test_injection_tools.py and adapt).\n"
        f"3. agents/roster.py ................ apply scaffold_out/{name}_roster_patch.py (import,\n"
        f"   TEAM line, role brief, build_swarm entry). Bump the docstring agent count.\n"
        f"4. agents/agent_tools.py ........... add \"{label}\" to the _RECRUITABLE frozenset.\n"
        f"   This allowlist is the code-enforced gate on what the Commander may recruit —\n"
        f"   editing it is a deliberate operator action, never automatic.\n"
        f"5. swarm/seed.py .................. add \"{label}\" to the SWARM list (+ the comment).\n"
        f"6. agent_config.example.yaml ...... add a {label} stanza (placeholders).\n"
        f"7. agent_config.yaml (gitignored) . register {label} on Band, paste agent_id + api_key.\n"
        f"8. tools/recon_tools.py (optional) . to auto-recommend this specialist, add a\n"
        f"   _live('/your/path') branch to crawltarget() and map a candidate -> {label}\n"
        f"   in the Control Center CAND_TO_AGENT (viewer/index.html).\n\n"
        f"Run `uv run --extra dev ruff check tools/{name}_tools.py` and the test suite before wiring live.\n"
    )


_SAFE_SCOPE_BANNER = (
    "DEMO SAFE SCOPE: only generate specialists targeting authorized lab targets "
    "(e.g. localhost:3000 running OWASP Juice Shop). Never point --target-path at a "
    "production host. The scope_guard blocks out-of-scope probes at runtime, but "
    "authorizing the target in advance is the operator's obligation, not the tool's."
)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="python -m tools.scaffolder",
        description="Generate a governed offensive-test specialist (leash-by-construction).",
    )
    p.add_argument("--name", required=True, help="snake_case slug; module + capability label")
    p.add_argument("--owasp-class", required=True, dest="owasp_class", help="e.g. 'OWASP A03', 'OWASP API8'")
    p.add_argument("--target-path", required=True, dest="target_path", help="default in-scope path, e.g. /graphql")
    p.add_argument("--payload", default="", help="probe body appended to the path (URL-encoded by the tool)")
    p.add_argument("--marker", default="", help="unique token expected back; required for marker_in_body")
    p.add_argument("--confirm-condition", dest="confirm_condition", default="marker_in_body", choices=_CONFIRM_MODES)
    p.add_argument("--severity", default="high", choices=_SEVERITIES)
    p.add_argument("--finding-type", dest="finding_type", default="", help="slug for record_finding; defaults to --name")
    p.add_argument("--description", required=True, help="one sentence; used in the docstring and role brief")
    p.add_argument("--dry-run", action="store_true", help="print artifacts to stdout, write nothing")
    args = p.parse_args(argv)
    if not args.finding_type:
        args.finding_type = args.name

    _validate(args)

    module = render_module(args)
    roster_patch = render_roster_patch(args)
    wiring_patch = render_wiring_patch(args)
    module_path = _TOOLS_DIR / f"{args.name}_tools.py"

    if args.dry_run:
        print(f"# ===== tools/{args.name}_tools.py =====\n{module}")
        print(f"# ===== scaffold_out/{args.name}_roster_patch.py =====\n{roster_patch}")
        print(f"# ===== scaffold_out/{args.name}_wiring_patch.txt =====\n{wiring_patch}")
        print(_SAFE_SCOPE_BANNER, file=sys.stderr)
        return 0

    if module_path.exists():
        print(f"refused: {module_path} already exists — not overwriting.", file=sys.stderr)
        return 1

    _OUT_DIR.mkdir(exist_ok=True)
    module_path.write_text(module)
    (_OUT_DIR / f"{args.name}_roster_patch.py").write_text(roster_patch)
    (_OUT_DIR / f"{args.name}_wiring_patch.txt").write_text(wiring_patch)

    print(f"generated tools/{args.name}_tools.py (capability leash-{args.name.replace('_', '-')})")
    print(f"wiring guide -> tools/scaffold_out/{args.name}_wiring_patch.txt")
    print(_SAFE_SCOPE_BANNER, file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
